# Generated by Django 5.2.7 on 2025-10-25 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movementrequest_id_alter_purchaseorder_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_receipt',
            field=models.FileField(blank=True, null=True, upload_to='po_delivery_receipts/'),
        ),
        migrations.CreateModel(
            name='PurchasingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Alasan mengapa packing list tidak sesuai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('po_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.purchaseorder')),
                ('reported_by', models.ForeignKey(limit_choices_to={'groups__name': 'Warehouse Manager'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
