# Generated by Django 5.2.7 on 2025-11-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_purchaseorder_delivery_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_wm',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Warehouse Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending_Approval', 'Pending WH Approval'), ('Rejected', 'Rejected by WH'), ('Pending', 'Pending Delivery'), ('Delivered', 'Delivered'), ('Finished', 'Finished')], default='Pending_Approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Warehouse Approval'), ('Approved_Buy', 'Approved (Need Purchase)'), ('Received', 'Received'), ('Issued', 'Issued to Technician'), ('Rejected', 'Rejected by Lead')], default='Pending', max_length=20),
        ),
    ]
