# Generated by Django 5.2.7 on 2025-11-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_purchaseorder_approved_by_wm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(help_text="Nama unik spare part, cth: 'Sensor Tipe X'", max_length=255, unique=True)),
                ('part_sku', models.CharField(blank=True, help_text='SKU internal untuk spare part ini', max_length=100, null=True, unique=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, help_text='Jumlah stok yang ada di gudang')),
                ('location', models.CharField(blank=True, help_text='Lokasi rak di gudang, cth: B-01-TOP', max_length=100, null=True)),
                ('primary_supplier', models.CharField(blank=True, help_text='Nama supplier utama part ini', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('On_Order', 'On Order (Dipesan)'), ('In_QC', 'In QC'), ('Out_Of_Stock', 'Out of Stock')], default='Out_Of_Stock', max_length=20)),
            ],
        ),
    ]
