# Generated by Django 5.2.7 on 2025-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_movementrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementrequest',
            name='receipt_form',
            field=models.FileField(blank=True, null=True, upload_to='movement_receipts/'),
        ),
    ]
