# Generated by Django 5.2.7 on 2025-11-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_movementrequest_receipt_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcform',
            name='final_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcform',
            name='final_lead_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcform',
            name='installation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcform',
            name='installation_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcform',
            name='photo_after_install',
            field=models.ImageField(blank=True, null=True, upload_to='qc_photos/after/'),
        ),
        migrations.AddField(
            model_name='qcform',
            name='photo_before_install',
            field=models.ImageField(blank=True, null=True, upload_to='qc_photos/before/'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='status',
            field=models.CharField(choices=[('Receiving', 'Receiving'), ('QC', 'In QC'), ('QC_PENDING', 'Pending Lead Approval'), ('AWAITING_INSTALL', 'Awaiting Part Installation'), ('PENDING_FINAL_CHECK', 'Pending Final Check'), ('Ready', 'Ready'), ('Delivering', 'Delivering to Shop'), ('Shop', 'Ready Shop')], default='Receiving', max_length=20),
        ),
    ]
