# Generated by Django 5.2.7 on 2025-11-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_qcform_final_approval_at_qcform_final_lead_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='lead_receipt_approver',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lead Technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_part_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='lead_receipt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Warehouse Approval'), ('Approved_Buy', 'Approved (Need Purchase)'), ('Received', 'Received'), ('PENDING_LEAD_RECEIPT', 'Pending Lead Receipt Approval'), ('Issued', 'Issued to Technician'), ('Rejected', 'Rejected by Lead')], default='Pending', max_length=20),
        ),
    ]
