# Generated by Django 5.2.8 on 2025-11-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sparepartrequest_lead_receipt_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcform',
            name='final_managed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp final check (approve/reject)', null=True),
        ),
    ]
