# Generated by Django 5.2.8 on 2025-11-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_qcform_final_managed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcform',
            name='qc_document_file',
            field=models.FileField(blank=True, help_text='File QC form (PDF, docx, etc.)', null=True, upload_to='qc_documents/'),
        ),
    ]
