# Generated by Django 5.2.8 on 2025-11-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_qcform_qc_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='installation_photos/')),
                ('photo_type', models.CharField(choices=[('before', 'Before Installation'), ('after', 'After Installation')], max_length=10)),
                ('remarks', models.CharField(blank=True, help_text='Keterangan foto', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qc_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.qcform')),
            ],
        ),
    ]
