# Generated by Django 5.2.8 on 2025-11-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_installationphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartinventory',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('On_Order', 'On Order (Dipesan)'), ('In_QC', 'In QC'), ('Out_Of_Stock', 'Out of Stock'), ('Pending_Adjustment', 'Pending Adjustment')], default='Out_Of_Stock', max_length=20),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_system', models.PositiveIntegerField()),
                ('quantity_actual', models.PositiveIntegerField(help_text='Jumlah fisik hasil perhitungan')),
                ('reason', models.TextField(help_text='Alasan penyesuaian (cth: Stock opname, barang rusak, hilang)')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('managed_at', models.DateTimeField(blank=True, null=True)),
                ('managed_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Purchasing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_managed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(limit_choices_to={'groups__name': 'Warehouse Manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments_requested', to=settings.AUTH_USER_MODEL)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='app.sparepartinventory')),
            ],
        ),
    ]
