# Generated by Django 5.2.8 on 2025-11-15 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_sparepartinventory_status_stockadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartinventory',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('PURCHASE', 'New Purchase'), ('RETURN', 'Old Part Return')], default='MANUAL', max_length=10),
        ),
        migrations.CreateModel(
            name='ReturnedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name_reported', models.CharField(help_text='Nama part lama yang dilaporkan Teknisi', max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('lead_assigned_sku', models.CharField(blank=True, help_text='SKU part lama yang diisi oleh Lead', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending_Lead', 'Pending Lead Approval'), ('Approved', 'Approved (In Stock)'), ('Rejected', 'Rejected by Lead')], default='Pending_Lead', max_length=20)),
                ('managed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_lead', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lead Technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returned_parts', to=settings.AUTH_USER_MODEL)),
                ('qc_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_parts', to='app.qcform')),
            ],
        ),
    ]
