# Generated by Django 5.2.8 on 2025-11-15 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sparepartinventory_origin_returnedpart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='status',
            field=models.CharField(choices=[('Receiving', 'Receiving'), ('QC', 'In QC'), ('QC_PENDING', 'Pending Lead Approval'), ('AWAITING_INSTALL', 'Awaiting Part Installation'), ('PENDING_FINAL_CHECK', 'Pending Final Check'), ('Ready', 'Ready'), ('Delivering', 'Delivering to Shop'), ('Shop', 'Ready Shop'), ('Booked', 'Booked'), ('Sold', 'Sold')], default='Receiving', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('customer_phone', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, help_text='Harga final penjualan', max_digits=10)),
                ('shipping_type', models.CharField(blank=True, help_text='Contoh: JNE, J&T, Diambil Sendiri', max_length=100, null=True)),
                ('shipping_receipt', models.FileField(blank=True, help_text='Resi Pengiriman', null=True, upload_to='sales/shipping_receipts/')),
                ('proof_of_receipt', models.FileField(blank=True, help_text='Bukti Penerimaan oleh Customer', null=True, upload_to='sales/proof_of_receipts/')),
                ('status', models.CharField(choices=[('Pending', 'Pending Payment'), ('Booked', 'Booked'), ('Sold', 'Sold'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_person', models.ForeignKey(limit_choices_to={'groups__name': 'Sales'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(limit_choices_to={'status': 'Shop'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='app.sku')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('proof_of_transfer', models.FileField(upload_to='sales/payment_proofs/')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.salesorder')),
            ],
        ),
    ]
