# Generated by Django 5.2.8 on 2025-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_sku_status_salesorder_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp saat bukti penerimaan diupload', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp saat resi pengiriman diupload', null=True),
        ),
    ]
