# Generated by Django 5.2.8 on 2025-11-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_salesorder_completed_at_salesorder_shipped_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('customer_phone', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Jumlah unit yang di-quote')),
                ('price', models.DecimalField(decimal_places=0, help_text='Harga yang ditawarkan', max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent to Customer'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Converted', 'Converted to Order')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_person', models.ForeignKey(limit_choices_to={'groups__name': 'Sales'}, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='app.sku')),
            ],
        ),
    ]
