# Generated by Django 5.2.8 on 2025-11-20 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotation',
            name='extra_discount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Diskon tambahan (Rp)', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
