# Generated by Django 5.2.8 on 2025-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_quotation_date_quotation_extra_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Harga Beli Total PO dari Supplier', max_digits=10, null=True),
        ),
    ]
