# Generated by Django 5.2.8 on 2025-11-23 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_purchaseorder_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='issued_spare_part',
            field=models.ForeignKey(blank=True, help_text='Part dari inventory yang dikeluarkan oleh WM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_requests', to='app.sparepartinventory'),
        ),
    ]
