# Generated by Django 5.2.8 on 2025-11-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sparepartrequest_issued_spare_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, help_text='Order hasil konversi dari quotation ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_quotations', to='app.salesorder'),
        ),
    ]
