# Generated by Django 5.2.8 on 2025-11-28 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_quotation_converted_to_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama Store/Outlet', max_length=100, unique=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Apakah store ini aktif')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Master Role yang menugaskan', limit_choices_to={'groups__name': 'Master Role'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.OneToOneField(help_text='User Sales yang ditugaskan', limit_choices_to={'groups__name': 'Sales'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_assignment', to=settings.AUTH_USER_MODEL)),
                ('assigned_store', models.ForeignKey(help_text='Store tempat Sales ditugaskan', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_sales', to='app.store')),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='current_store',
            field=models.ForeignKey(blank=True, help_text="Store tempat SKU ini berada saat status='Shop'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus_in_store', to='app.store'),
        ),
    ]
