# Generated by Django 5.2.8 on 2025-11-30 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_store_salesassignment_sku_current_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementrequest',
            name='requested_by_shop',
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='received_by_sales',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='requested_by_store',
            field=models.ForeignKey(blank=True, help_text='Store Tujuan Pengiriman', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='app.store'),
        ),
        migrations.AlterField(
            model_name='movementrequest',
            name='sku_to_move',
            field=models.ForeignKey(limit_choices_to={'status': 'Ready'}, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='app.sku'),
        ),
        migrations.AlterField(
            model_name='movementrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Delivery'), ('Delivering', 'Delivering'), ('Received', 'Received at Shop')], default='Delivering', max_length=20),
        ),
        migrations.AlterField(
            model_name='sku',
            name='current_store',
            field=models.ForeignKey(blank=True, help_text="Store tempat SKU ini berada saat status='Shop'", limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus_in_store', to='app.store'),
        ),
    ]
