# Generated by Django 5.2.8 on 2025-11-30 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_clean_sku_shelf_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_location', models.CharField(help_text='Lokasi fisik rak, cth: A1-01', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available (Hijau)'), ('Used', 'Used (Merah)')], default='Available', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupied_by_sku', models.OneToOneField(blank=True, help_text='SKU yang saat ini menempati slot ini (null jika Available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_slot', to='app.sku')),
            ],
            options={
                'verbose_name': 'Slot Rak Gudang',
                'verbose_name_plural': 'Slot Rak Gudang',
                'ordering': ['rack_location'],
            },
        ),
        migrations.AlterField(
            model_name='sku',
            name='shelf_location',
            field=models.ForeignKey(blank=True, help_text='Slot rak tempat SKU ini diletakkan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_skus', to='app.rack'),
        ),
    ]
