# Generated by Django 5.2.8 on 2025-12-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rack_alter_sku_shelf_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='suggested_rack',
            field=models.ForeignKey(blank=True, help_text='Saran Lokasi Rak dari Purchasing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_pos', to='app.rack'),
        ),
    ]
