# Generated by Django 5.2.8 on 2025-12-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_purchaseorder_suggested_rack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='buy_price',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_po_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Harga Beli Total PO dari Supplier (Auto-Calculated)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SKUDetailPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_sku_id', models.CharField(help_text='ID Mesin / SKU Item', max_length=100)),
                ('machine_name', models.CharField(help_text='Nama Mesin / Tipe', max_length=255)),
                ('color', models.CharField(help_text='Warna Mesin', max_length=50)),
                ('po_price', models.DecimalField(decimal_places=0, help_text='Harga Beli PO per unit (Rp)', max_digits=10)),
                ('year', models.IntegerField(blank=True, help_text='Tahun pembuatan mesin (Opsional)', null=True)),
                ('purchase_order', models.ForeignKey(help_text='PO Induk dari detail mesin ini', on_delete=django.db.models.deletion.CASCADE, related_name='sku_details', to='app.purchaseorder')),
            ],
        ),
    ]
