# Generated by Django 5.2.8 on 2025-12-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_purchaseorder_buy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='suggested_rack',
        ),
    ]
